Repository dswan36/acprox, pull requests merged in 2024-06, with the labels that each got.

#26 [ Hotfix ] : Fix dependabot ecosystem
  .github/dependabot.yml
Labels: bug, dependencies

#31 [ Dependencies ] : Merge Deps into Main
  package-lock.json
  package.json
Labels: dependencies

#35 [ Style ] : Add Self hosting link and Vercel badge to Readme
  README.md
Labels: formatting, Internal

#38 [ Feature ] : Link to EZPROX in URLMAKER
  public/urlmaker.html
Labels: documentation, formatting, Proxy, Design

#36 [ Style ] : Update wording for some features
  public/README.md
  public/apps.html
  public/emulator.html
  public/index.html
  public/load.html
  public/search.html
  public/settings.html
  public/urlmaker.html
Labels: enhancement, formatting, Design

#39 [ B:Feature ] : EZPROX Link & Style Changes
  README.md
  public/README.md
  public/apps.html
  public/emulator.html
  public/index.html
  public/load.html
  public/search.html
  public/settings.html
  public/urlmaker.html
Labels: documentation, formatting, Proxy, Design
