Repository dswan36/acprox, pull requests merged in 2024-08, with the labels that each got.

#49 [ Style ] : Add a contact button to the main page
  public/contact.html
  public/index.html
  public/urlmaker.html
Labels: formatting, Design

#51 [ Style ] : New Logo
  README.md
  public/assets/acprox.png
  public/assets/ezprox.png
  public/contact.html
  public/index.html
  public/urlmaker.html
Labels: documentation, enhancement, Internal, Design

#53 [ Style ] : Contact info in logger.
  public/js/preload.js
  public/registersw.js
Labels: documentation, enhancement, javascript, Internal

#54 [ Depreciation ] : RestyledGHAPP
  .github/workflows/restyled.yml
Labels: dependencies, Internal

#55 [ Style ] : Replace Depreciation text with Important Alert
  README.md
Labels: documentation, Internal

#57 [ Style ] : Add email request button on HP
  public/index.html
Labels: enhancement, Design

#60 [ Smells ] : Cleanup code for DST
  index.js
  public/assets/data/apps.js
  public/js/apps.js
  public/js/games.js
  public/js/index.js
  public/js/load.js
  public/js/preload.js
  public/js/search.js
  public/js/settings.js
Labels: bug, enhancement, javascript, formatting, Design
